name: Build
on:
  push:
    branches:
      - main
      - branch-*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: sonar-s-public
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        with:
          version: 2026.1.8
      - name: Build, Test, Analyze and deploy
        uses: SonarSource/ci-github-actions/build-yarn@v1
        with:
          artifactory-reader-role: public-reader
          artifactory-deploy-repo: sonarsource-npm-public-qa
          artifactory-deployer-role: qa-deployer
          deploy-pull-request: true
          sonar-platform: next
          cache-yarn: true

  promote:
    name: Promote
    needs:
      - build
    runs-on: sonar-xs-public
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: SonarSource/ci-github-actions/promote@v1
        with:
          promote-pull-request: true

  slack-notifications:
    runs-on: github-ubuntu-latest-s # Public GH runner is required, runners starting with sonar-* do not support this action
    if: failure() && (contains(fromJSON('["main", "master"]'), github.ref_name) || startsWith(github.ref_name, 'branch-'))
    needs: [ build, promote ]
    permissions:
      id-token: write
    steps:
      - name: Vault Secrets
        id: secrets
        uses: SonarSource/vault-action-wrapper@v3
        with:
          secrets: |
            development/kv/data/slack token | SLACK_TOKEN;

      - name: Slack Notification rtCamp
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661  # v2.3.3
        env:
          SLACK_TOKEN: >-
            ${{ fromJSON(steps.secrets.outputs.vault).SLACK_TOKEN }}
          SLACK_CHANNEL: ops-sonarcloud-webapp
          SLACK_TITLE: Build failed ðŸš¨
          SLACK_USERNAME: BuildBot
          SLACK_COLOR: danger
          SLACK_MESSAGE: |
            Workflow failed in ${{ github.repository }}
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Branch: ${{ github.head_ref || github.ref_name }}
