name: Unified Dogfooding scans
on:
  schedule:
    # Run the workflow every day at 03:00 UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  shadow-scans:
    runs-on: sonar-s-public
    name: Build and run shadow scans
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: jdx/mise-action@e3d7b8d67a7958d1207f6ed871e83b1ea780e7b0 # v3.3.1
        with:
          version: 2025.9.12
      - uses: SonarSource/ci-github-actions/build-yarn@v1
        with:
          run-shadow-scans: true

      - name: Run IRIS
        uses: SonarSource/unified-dogfooding-actions/run-iris@v1
        with:
          primary_project_key: "SonarSource_echoes-react"
          primary_platform: "Next"
          shadow1_project_key: "SonarSource_echoes-react"
          shadow1_platform: "SQC-EU"
          shadow2_project_key: "SonarSource_echoes-react"
          shadow2_platform: "SQC-US"

  slack-notifications:
    runs-on: github-ubuntu-latest-s # Public GH runner is required, runners starting with sonar-* do not support this action
    if: failure()
    needs: [ shadow-scans ]
    permissions:
      id-token: write
    steps:
      - name: Vault Secrets
        id: secrets
        uses: SonarSource/vault-action-wrapper@v3
        with:
          secrets: |
            development/kv/data/slack token | SLACK_TOKEN;

      - name: Slack Notification rtCamp
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661  # v2.3.3
        env:
          SLACK_TOKEN: >-
            ${{ fromJSON(steps.secrets.outputs.vault).SLACK_TOKEN }}
          SLACK_CHANNEL: ops-sonarcloud-webapp
          SLACK_TITLE: Shadow scans failed ðŸš¨
          SLACK_USERNAME: BuildBot
          SLACK_COLOR: danger
          SLACK_MESSAGE: |
            Workflow failed in ${{ github.repository }}
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Branch: ${{ github.head_ref || github.ref_name }}
